sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite
matrix:
  allow_failures:
    - rvm: rbx-2

before_install:
  - ruby ci/copy_database_config.rb

before_script:
  - mysql -e 'create database calagator_test;'
  - psql -c 'create database calagator_test;' -U postgres
  - bundle exec rake db:migrate
  - cp "config/secrets.yml.sample" "config/secrets.yml"
  - bundle exec rake sunspot:solr:start
script:
  - bundle exec rake spec --trace
cache: bundler

