sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - rbx-2
env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite3
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile

before_script:
  - bundle exec bin/calagator new spec/dummy --dummy --database=$DB --postgres-username=postgres
  - bundle exec rake app:db:migrate app:db:seed
  - bundle exec rake app:sunspot:solr:start_with_waiting

script:
  - bundle exec rake spec --trace
cache: bundler

