sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - rbx-2
env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2

before_install:
  - ruby ci/copy_database_config.rb

before_script:
  - bin/calagator new spec/dummy
  - mysql -e 'create database calagator_test;'
  - psql -c 'create database calagator_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start_with_waiting
script:
  - bundle exec rake spec --trace
cache: bundler

