add_ons:
  chrome: stable

language: ruby

rvm:
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - rbx-2

jdk:
  - openjdk8

gemfile:
  - gemfiles/rails_4_2.gemfile

services:
  - mysql
  - postgresql

env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite3

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.5.5
    - rvm: rbx-2

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - bundle exec bin/calagator new spec/dummy --dummy --database=$DB --postgres-username=postgres
  - travis_retry bundle exec rake app:db:migrate app:db:seed
  - travis_retry bundle exec rake app:sunspot:solr:start_with_waiting

script:
  - bundle exec rake spec --trace
cache: bundler
