sudo: false
language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx-2

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile

env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite3

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
  exclude:
    - rvm: rbx-2
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails_4_1.gemfile

before_script:
  - bundle exec bin/calagator new spec/dummy --dummy --database=$DB --postgres-username=postgres
  - travis_retry bundle exec rake app:db:migrate app:db:seed
  - travis_retry bundle exec rake app:sunspot:solr:start_with_waiting

script:
  - bundle exec rake spec --trace
cache: bundler

