language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-2.1.1

  ## Don't test 1.9.2 because people shouldn't be using it.
  # - 1.9.2

  ## Don't test REE because it's compatible enough with 1.8.7.
  # - ree

  ## JRuby is not compatible, see Gemfile for details.
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
before_install:
  - ruby ci/copy_database_config.rb
before_script:
  - mysql -e 'create database calagator_test;'
  - psql -c 'create database calagator_test;' -U postgres
  - bundle exec rake db:migrate
  - cp "config/secrets.yml.sample" "config/secrets.yml"
script:
  - bundle exec rake spec --trace
