<%
# database.yml customizer
# =======================
#
# Load database configuration from this custom file if it exists:
custom  = "#{File.dirname(__FILE__)}/config/database~custom.yml"
# ...otherwise, load database configuration from this default file:
default = "#{File.dirname(__FILE__)}/config/database~postgresql.sample.yml"
%>
<%= ERB.new(File.read(File.exist?(custom) ? custom : default)).result() %>
