#
# This file configures the NewRelic RPM Agent, NewRelic RPM monitors Rails 
# applications with deep visibility and low overhead.  For more information, 
# visit www.newrelic.com.
#
# This configuration file is custom generated for mail@reidbeels.com at Calagator
#
# here are the settings that are common to all environments
common: &default_settings
  # ============================== LICENSE KEY ===============================
  # You must specify the licence key sent to you by New Relic for your agent to
  # communicate with the New Relic RPM service.  
  license_key: '7b631f4fe700640f4a7a90a672fb76f6f8a3f46e'

  # the 'enabled' setting is used to turn on the NewRelic Agent.  When false,
  # your application is not instrumented and the Agent does not start up or
  # collect any data; it is a complete shut-off.
  #
  # when turned on, the agent collects performance data by inserting lightweight
  # tracers on key methods inside the rails framework and asynchronously aggregating
  # and reporting this performance data to the NewRelic RPM service at NewRelic.com.
  # below.
  enabled: false

  # The newrelic agent generates its own log file to keep its logging information
  # separate from that of your application.  Specify its log level here.
  log_level: info

  # The newrelic agent communicates with the RPM service via http by default.
  # If you want to communicate via https to increase security, then turn on
  # ssl by setting this value to true.  Note, this will result in increased
  # CPU overhead to perform the encryption involved in SSL communication, but this
  # work is done asynchronously to the threads that process your application code, so
  # it should not impact response times.
  ssl: false

# override default settings based on your application's environment

# NOTE if your application has other named environments, you should
# provide newrelic conifguration settings for these enviromnents here.

development:
  <<: *default_settings
  # turn off communication to RPM service in development mode.
  # NOTE: for initial evaluation purposes, you may want to temporarily turn
  # the agent on in developmen mode.
  enabled: false
  
  # run the agent in development mode.  This mode collects recent transaction performance
  # information in memory (no communication to any external service) for localhost
  # performance analysis.  To see high level performance information of your app
  # in development mode, simply point your browser to http://localhost:3000/newrelic
  developer: true

test:
  <<: *default_settings
  # it almost never makes sense to turn on the agent when running unit, functional or
  # integration tests or the like.
  enabled: false

# Turn on the agent in production for 24x7 monitoring.  NewRelic testing shows
# an average performance impact of < 5 ms per transaction, so you can leave this on
# all the time without incurring any user-visible performance degredation.
production:
  <<: *default_settings
  enabled: true

# many applications have a staging environment which behaves identically to production,
# support for that environment is provided here.  By default, the staging environment has
# the agent turned on.
staging:
  <<: *default_settings
  enabled: true

